# Generated by Django 6.0.2 on 2026-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='crew',
            field=models.ManyToManyField(related_name='journeys', to='station.crew'),
        ),
    ]
